---

- name: Ensures {{ destFolder }} dir exists
  file:
    path: "{{ destFolder }}"
    state: directory

- template:
    src: "{{ item }}"
    dest: "{{ destFolder }}/{{ item }}"
  loop:
    - "override.yml"

- name: Register deployed count chart
  shell: helm ls | grep {{ releaseName }} | wc -l
  register: deployed

- name: Install Prometheus
  shell: |
    helm install stable/prometheus \
    --name {{ releaseName }} \
    -f {{ destFolder }}/override.yml \
    --wait
  when: deployed.stdout == "0"
